name: Landing Zone Bicep Deployment

on:
  push:
    branches:
      - sbx
  pull_request:

permissions:
      id-token: write
      contents: write
      pull-requests: write

jobs:
  deploy:
    name: 'bicep deployment azure landing zone'
    runs-on: ubuntu-latest
    environment: sbx

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Bicep CLI
      run: |
        az bicep install

    - name: Preview Deployment
      run: |
        az deployment sub what-if \
          --location 'eastus' \
          --template-file main.bicep \
          --parameters @configs/nonprod/sbx-parameters.json
        
    - name: Deploy Bicep file
      if: github.ref == 'refs/heads/sbx' && github.event_name == 'push'    
      run: |
        az deployment sub create \
        --location 'eastus' \
        --template-file main.bicep \
        --parameters @configs/nonprod/sbx-parameters.json